// Build.gradle generated for instrumentation module resilience4j-retry_1.5

apply plugin: 'java'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

dependencies {
    implementation 'io.github.resilience4j:resilience4j-retry:2.0.0'


    // New Relic Java Agent dependencies
    implementation 'com.newrelic.agent.java:newrelic-agent:' + project.findProperty('java.agent.version')
    implementation 'com.newrelic.agent.java:newrelic-api:' + project.findProperty('java.agent.version')
    implementation 'com.newrelic.agent.java:agent-bridge:' + project.findProperty('java.agent.version')
    implementation fileTree(include: ['*.jar'], dir: '../test-lib')
}

jar {
    manifest {
        attributes 'Implementation-Title': 'com.newrelic.instrumentation.labs.resilience4j-retry_2.x'
        attributes 'Implementation-Vendor': 'New Relic Labs'
        attributes 'Implementation-Vendor-Id': 'com.newrelic.labs'
        attributes 'Implementation-Version': 1.0
    }
}

verifyInstrumentation {
    passesOnly 'io.github.resilience4j:resilience4j-retry:[2.0.0,)'
}
